version: 0.0
os: linux
files:
  - source: target/addition-service-1.0.0.jar
    destination: /home/ec2-user/apps/addition-service
hooks:
  ApplicationStart:
    - location: scripts/run-addition-service.sh
      runas: root